/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alpha: typeof import('./src/components/ColorPicker/Alpha.vue')['default']
    Checkboard: typeof import('./src/components/ColorPicker/Checkboard.vue')['default']
    ColorButton: typeof import('./src/components/ColorButton.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker/index.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu/index.vue')['default']
    EditableInput: typeof import('./src/components/ColorPicker/EditableInput.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckboxButton: typeof import('element-plus/es')['ElCheckboxButton']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FileInput: typeof import('./src/components/FileInput.vue')['default']
    FullscreenSpin: typeof import('./src/components/FullscreenSpin.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hue: typeof import('./src/components/ColorPicker/Hue.vue')['default']
    MenuContent: typeof import('./src/components/ContextMenu/MenuContent.vue')['default']
    Saturation: typeof import('./src/components/ColorPicker/Saturation.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    TextColorButton: typeof import('./src/components/TextColorButton.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
