import './object/Image'
import './object/Group'
import './object/Polygon'
import './object/BarCode'
import './object/QRCode'
import './object/GuideLine'
import './object/SVGImage'
import './object/CurvedText'