import './object/Image'
import './object/Group'
import './object/Polygon'
import './object/BarCode'
import './object/QRCode'
import './object/ReferenceLine'
import './object/SVGImage'
import './object/CurvedText'
import './object/ArcText'
import './object/RotateText'
// import './object/IText'