/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alpha: typeof import('./../components/ColorPicker/Alpha.vue')['default']
    Checkboard: typeof import('./../components/ColorPicker/Checkboard.vue')['default']
    ColorButton: typeof import('./../components/ColorButton.vue')['default']
    ColorPicker: typeof import('./../components/ColorPicker/index.vue')['default']
    Contextmenu: typeof import('./../components/Contextmenu/index.vue')['default']
    EditableInput: typeof import('./../components/ColorPicker/EditableInput.vue')['default']
    ExportImage: typeof import('./../components/FileExport/ExportImage.vue')['default']
    ExportJSON: typeof import('./../components/FileExport/ExportJSON.vue')['default']
    ExportPDF: typeof import('./../components/FileExport/ExportPDF.vue')['default']
    ExportPSD: typeof import('./../components/FileExport/ExportPSD.vue')['default']
    ExportSVG: typeof import('./../components/FileExport/ExportSVG.vue')['default']
    Extraction: typeof import('./../components/ImageMatting/extraction.vue')['default']
    FileExport: typeof import('./../components/FileExport/index.vue')['default']
    FileInput: typeof import('./../components/FileInput.vue')['default']
    FileUpload: typeof import('./../components/FileUpload/index.vue')['default']
    FullscreenSpin: typeof import('./../components/FullscreenSpin.vue')['default']
    HomePopover: typeof import('./../components/HomePopover.vue')['default']
    Hue: typeof import('./../components/ColorPicker/Hue.vue')['default']
    ImageFillColor: typeof import('./../components/ImageFillColor.vue')['default']
    ImageMatting: typeof import('./../components/ImageMatting/index.vue')['default']
    Lang: typeof import('./../components/Lang/index.vue')['default']
    LinePointMarker: typeof import('./../components/LinePointMarker.vue')['default']
    LoginDialog: typeof import('./../components/LoginDialog/index.vue')['default']
    Matting: typeof import('./../components/ImageMatting/matting.vue')['default']
    MenuContent: typeof import('./../components/Contextmenu/MenuContent.vue')['default']
    OpenGpt: typeof import('./../components/GPTModal/OpenGpt.vue')['default']
    ReferencePopover: typeof import('./../components/ReferencePopover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Saturation: typeof import('./../components/ColorPicker/Saturation.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    SwipeInput: typeof import('./../components/SwipeInput.vue')['default']
    TextColorButton: typeof import('./../components/TextColorButton.vue')['default']
  }
}
